-- CreateEnum
CREATE TYPE "TipoPatrimonio" AS ENUM ('ARQUEOLOGICO', 'ARQUITECTONICO', 'ARTISTICO', 'DOCUMENTAL', 'ETNOGRAFICO', 'INDUSTRIAL', 'MUSICAL');

-- CreateEnum
CREATE TYPE "EstiloBien" AS ENUM ('ACADEMICISMO', 'BARROCO', 'CLASICISMO', 'ECLECTICISMO', 'FLAMENCO', 'GOTICO', 'INDIGENISMO', 'MODERNISMO', 'MUDEJAR', 'NEOCANARIO', 'NEOCLASICO', 'NEOGÓTICO', 'RACIONALISMO', 'RENACIMIENTO', 'ROMANTICISMO', 'TRADICIONAL_POPULAR');

-- AlterEnum
ALTER TYPE "TipoBien" ADD VALUE 'INMATERIAL';

-- AlterTable
ALTER TABLE "bienes" ADD COLUMN     "estilo" "EstiloBien",
ADD COLUMN     "municipio" VARCHAR(100),
ADD COLUMN     "tipoPatrimonio" "TipoPatrimonio";
